[tool.poetry]
name = "kora"
version = "0.1.0"
description = ""
authors = ["Gabriele Mongiano <gabriele.mongiano@crea.gov.it>"]
readme = "README.md"

[tool.poetry.dependencies]
django-countries = "*"
django-crispy-forms = "*"
crispy-bootstrap4 = "*"
django-filter = "*"
django-forms-dynamic = "*"
django-htmx = "*"
django-tables2 = "*"
django-view-breadcrumbs = "*"
django-widget-tweaks = "*"
djangorestframework = "*"
numpy = "*"
pandas = "*"
psycopg2-binary = "*"
python = "^3.10"
tablib = "*"
django = "4.2"


[tool.poetry.group.dev.dependencies]
debugpy = "*"
django-extensions = "*"
django-filter-stubs = "*"
django-stubs = "*"
django-types = "*"
flake8 = "*"
ipython = "*"
pandas-stubs = "*"
pyflyby = "*"
pyflakes = "*"
autoimport = "*"
pyright = "^1.1.344"
ruff = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = "py311"
select = [
    "ALL",
]
ignore = [
    "ANN", # flake8-annotations
    "COM", # flake8-commas
    "C90", # mccabe complexity
    "EXE", # flake8-executable
    "T10", # debugger
    "TID", # flake8-tidy-imports
    "E402",   # false positives for local imports
    "I001",   # import sorting
    "E501",   # line too long
    "TRY003", # external messages in exceptions are too verbose
    "TD002",
    "TD003",
    "FIX002", # too verbose descriptions of todos
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"