[project]
name = "kora"
version = "0.1.0"
description = "An open-source web app to manage plant genetic resources data."
readme = "README.md"
authors = [
    { name = "Gabriele Mongiano", email = "gabriele.mongiano@crea.gov.it" },
]
maintainers = [
    { name = "Gabriele Mongiano", email = "gabriele.mongiano@crea.gov.it" },
]
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
]

requires-python = ">=3.12"

[project.urls]
issues = "https://github.com/kofm/kora/issues"
homepage = "https://github.com/kofm/kora"
repository = "https://github.com/kofm/kora"

[tool.ruff]

target-version = "py311"
line-length = 120
exclude = [
    "**/migrations/*.py",
    ".venv",
    "venv",
    ".git",
    "__pypackages__",
    "dist",
    "node_modules",
    "static",
    "site-packages",
]

[tool.ruff.lint]

select = ["A", "B", "C4", "E", "F", "I", "DJ", "INP", "TID", "UP", "YTT"]
ignore = ["INP001"]
fixable = ["A", "B", "C4", "E", "F", "I", "TID", "UP"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.pydocstyle]
convention = "pep257"
