# Generated by Django 3.1.4 on 2020-12-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("register", "0002_auto_20201207_2033"),
    ]

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeric_id", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="describe.protocol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeric_id", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="describe.trait"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expression",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recording_date", models.DateField()),
                ("georeference_lat", models.FloatField()),
                ("georeference_lon", models.FloatField()),
                (
                    "description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="describe.description",
                    ),
                ),
                (
                    "state_of_expression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="describe.state"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="description",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="describe.protocol"
            ),
        ),
        migrations.AddField(
            model_name="description",
            name="variety",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="variety",
                to="register.plantvariety",
            ),
        ),
    ]
