# Generated by Django 4.1.2 on 2022-10-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name/identifier of the description', max_length=200)),
            ],
            options={
                'ordering': ['variety__name'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the protocol', max_length=200)),
                ('url_ref', models.URLField(blank=True, help_text='the URL reference to the protocol', null=True)),
                ('plantspecies', models.ForeignKey(help_text='reference to the specie it is meant to use with', on_delete=django.db.models.deletion.PROTECT, to='register.plantspecies')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_id', models.IntegerField(blank=True, help_text='The numeric identifier of the trait', null=True)),
                ('description', models.CharField(help_text="The trait's description", max_length=200)),
                ('grouping', models.BooleanField(default=False)),
                ('protocol', models.ForeignKey(blank=True, help_text='The reference protocol of the trait', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traits', to='describe.protocol')),
            ],
            options={
                'ordering': ['numeric_id'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_id', models.IntegerField(blank=True, help_text='a numeric ID that can be associated with the trait', null=True)),
                ('description', models.CharField(max_length=200)),
                ('related_states', models.ManyToManyField(to='describe.state')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='describe.trait')),
            ],
            options={
                'ordering': ['numeric_id'],
            },
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='describe.description')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='describe.state')),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='protocol',
            field=models.ForeignKey(help_text='reference to the protocol used to make the description;            this will define which Traits will be available', on_delete=django.db.models.deletion.PROTECT, related_name='descriptions', to='describe.protocol'),
        ),
        migrations.AddField(
            model_name='description',
            name='variety',
            field=models.ForeignKey(help_text='the variety to which the description refers to', on_delete=django.db.models.deletion.RESTRICT, to='register.plantvariety'),
        ),
    ]
