# Generated by Django 3.1.4 on 2020-12-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='numeric_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='describe.protocol'),
        ),
    ]
