# Generated by Django 4.0.4 on 2023-04-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.CharField(help_text='A descriptive text about the note', max_length=200),
        ),
        migrations.AlterField(
            model_name='state',
            name='numeric_id',
            field=models.IntegerField(blank=True, help_text='the numeric ID of the Note', null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.CharField(help_text="The characteristic's description", max_length=200),
        ),
        migrations.AlterField(
            model_name='trait',
            name='numeric_id',
            field=models.IntegerField(blank=True, help_text="The characteristic's numeric ID", null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='protocol',
            field=models.ForeignKey(blank=True, help_text='The reference protocol of the trait', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='describe.protocol'),
        ),
    ]
