# Generated by Django 3.1.4 on 2020-12-07 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("describe", "0002_auto_20201207_2043"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("georeference_lat", models.FloatField()),
                ("georeference_lon", models.FloatField()),
                ("measure_unit", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                (
                    "linked_trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="describe.trait"
                    ),
                ),
            ],
        ),
    ]
