# Generated by Django 3.2.18 on 2023-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0002_alter_state_description_alter_state_numeric_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='related_states',
            field=models.ManyToManyField(related_name='_describe_state_related_states_+', to='describe.State'),
        ),
    ]
