# Generated by Django 3.1.4 on 2020-12-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0003_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='numeric_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='describe.protocol'),
        ),
    ]
