# Generated by Django 3.2.18 on 2023-05-03 14:46

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0003_alter_state_related_states'),
    ]

    operations = [TrigramExtension(), UnaccentExtension()]
