# Generated by Django 4.2 on 2024-02-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0004_auto_20230503_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ('variety__name',)},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('numeric_id',)},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={'ordering': ('numeric_id',)},
        ),
        migrations.AddField(
            model_name='expression',
            name='note',
            field=models.CharField(blank=True, help_text='Add any additional information here.', max_length=512),
        ),
        migrations.AlterField(
            model_name='state',
            name='related_states',
            field=models.ManyToManyField(to='describe.state'),
        ),
    ]
