# Generated by Django 3.1.4 on 2020-12-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_auto_20201207_2033"),
        ("describe", "0004_auto_20201207_2102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="variety",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="register.plantvariety"
            ),
        ),
    ]
