# Generated by Django 4.2 on 2024-02-26 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_entity_options_alter_plantspecies_options_and_more'),
        ('describe', '0005_alter_description_options_alter_state_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expression',
            options={'ordering': ['state__numeric_id']},
        ),
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.CharField(help_text='The identifier of the description', max_length=200),
        ),
        migrations.AlterField(
            model_name='description',
            name='protocol',
            field=models.ForeignKey(help_text='Reference protocol used to make the description;            this will define which Traits will be available', on_delete=django.db.models.deletion.PROTECT, related_name='descriptions', to='describe.protocol'),
        ),
        migrations.AlterField(
            model_name='description',
            name='variety',
            field=models.ForeignKey(help_text='The variety to which the description refers to', on_delete=django.db.models.deletion.RESTRICT, to='register.plantvariety'),
        ),
    ]
