# Generated by Django 4.2 on 2024-05-10 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('describe', '0006_alter_expression_options_alter_description_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionsUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='expression',
            options={'ordering': ['state__trait__numeric_id']},
        ),
        migrations.CreateModel(
            name='DescriptionsUserListElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='describe.descriptionsuserlist')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='describe.description')),
            ],
            options={
                'unique_together': {('description', 'desc_list')},
            },
        ),
    ]
