# Generated by Django 5.0.7 on 2024-08-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0007_descriptionsuserlist_alter_expression_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionsuserlistelement',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='descriptionsuserlistelement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
