# Generated by Django 3.1.4 on 2020-12-13 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_auto_20201207_2033"),
        ("describe", "0007_auto_20201213_1019"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="url_ref",
            field=models.URLField(
                blank=True, help_text="the URL reference to the protocol", null=True
            ),
        ),
        migrations.AlterField(
            model_name="description",
            name="name",
            field=models.CharField(
                help_text="the name/identifier of the description", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="description",
            name="protocol",
            field=models.ForeignKey(
                help_text="reference to the protocol used to make the description;            this will define which Traits will be available",
                on_delete=django.db.models.deletion.PROTECT,
                to="describe.protocol",
            ),
        ),
        migrations.AlterField(
            model_name="description",
            name="variety",
            field=models.ForeignKey(
                help_text="the variety to which the description refers to",
                on_delete=django.db.models.deletion.RESTRICT,
                to="register.plantvariety",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="name",
            field=models.CharField(
                help_text="the name of the protocol", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="specie",
            field=models.ForeignKey(
                help_text="reference to the specie it is meant to use with",
                on_delete=django.db.models.deletion.PROTECT,
                to="register.plantspecies",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="numeric_id",
            field=models.IntegerField(
                blank=True,
                help_text="a numeric ID that can be associated with the trait",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trait",
            name="description",
            field=models.CharField(help_text="trait description", max_length=200),
        ),
        migrations.AlterField(
            model_name="trait",
            name="numeric_id",
            field=models.IntegerField(
                blank=True,
                help_text="the numeric identifier often used in official                     protocols",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Measure",
        ),
    ]
