# Generated by Django 5.1.4 on 2024-12-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("describe", "0008_alter_descriptionsuserlistelement_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="descriptionsuserlistelement",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="expression",
            options={"ordering": ("state__trait__numeric_id",)},
        ),
        migrations.AlterField(
            model_name="descriptionsuserlist",
            name="name",
            field=models.CharField(
                help_text="The identificative name of the list", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="url_ref",
            field=models.URLField(
                blank=True, default="", help_text="the URL reference to the protocol"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="numeric_id",
            field=models.IntegerField(help_text="the numeric ID of the Note"),
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together={("numeric_id", "trait")},
        ),
    ]
