# Generated by Django 3.1.4 on 2021-01-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0008_auto_20201213_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['numeric_id']},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={'ordering': ['numeric_id']},
        ),
        migrations.RemoveField(
            model_name='expression',
            name='georeference_lat',
        ),
        migrations.RemoveField(
            model_name='expression',
            name='georeference_lon',
        ),
        migrations.RemoveField(
            model_name='expression',
            name='recording_date',
        ),
        migrations.AlterField(
            model_name='state',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='describe.trait'),
        ),
    ]
