# Generated by Django 3.2.12 on 2022-02-11 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("describe", "0009_auto_20210106_1258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="description",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="expressions",
                to="describe.description",
            ),
        ),
        migrations.AlterField(
            model_name="trait",
            name="protocol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="traits",
                to="describe.protocol",
            ),
        ),
    ]
