# Generated by Django 5.1.4 on 2024-12-26 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("describe", "0009_alter_descriptionsuserlistelement_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="state",
            options={"ordering": ("trait", "numeric_id")},
        ),
        migrations.AlterField(
            model_name="trait",
            name="protocol",
            field=models.ForeignKey(
                help_text="The reference protocol of the trait",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traits",
                to="describe.protocol",
            ),
        ),
    ]
