# Generated by Django 3.2.12 on 2022-04-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0010_auto_20220211_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['variety__name']},
        ),
    ]
