# Generated by Django 4.0.4 on 2022-06-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0011_alter_description_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='describe.description'),
        ),
    ]
