# Generated by Django 5.1.6 on 2025-03-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("describe", "0011_auto_20250304_1942"),
        ("register", "0013_alter_plantspecies_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protocol",
            options={"ordering": ("name",)},
        ),
        migrations.RenameField(
            model_name="workspaceelement",
            old_name="desc_list",
            new_name="workspace",
        ),
        migrations.AlterField(
            model_name="protocol",
            name="plantspecies",
            field=models.ForeignKey(
                help_text="reference to the specie it is meant to use with",
                on_delete=django.db.models.deletion.PROTECT,
                to="register.plantspecies",
                verbose_name="Species",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="url_ref",
            field=models.URLField(
                blank=True,
                default="",
                help_text="the URL reference to the protocol",
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="description",
            field=models.CharField(
                help_text="A descriptive text about the state.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="numeric_id",
            field=models.IntegerField(help_text="Numbering code.", verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="trait",
            name="description",
            field=models.CharField(
                help_text="A descriptive, unique, and unambiguous name.",
                max_length=200,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="trait",
            name="grouping",
            field=models.BooleanField(
                default=False,
                help_text="Is this a highly discriminating characteristic?",
            ),
        ),
        migrations.AlterField(
            model_name="trait",
            name="numeric_id",
            field=models.IntegerField(
                blank=True, help_text="Numbering code.", null=True, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspaceelement",
            unique_together={("description", "workspace")},
        ),
    ]
