# Generated by Django 4.0.4 on 2022-07-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0012_alter_expression_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expression',
            old_name='state_of_expression',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='specie',
            new_name='plantspecies',
        ),
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.CharField(help_text="The trait's description", max_length=200),
        ),
        migrations.AlterField(
            model_name='trait',
            name='numeric_id',
            field=models.IntegerField(blank=True, help_text='The numeric identifier of the trait', null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='protocol',
            field=models.ForeignKey(blank=True, help_text='The reference protocol of the trait', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traits', to='describe.protocol'),
        ),
    ]
