# Generated by Django 5.1.6 on 2025-03-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("describe", "0012_alter_protocol_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
