# Generated by Django 4.0.4 on 2022-07-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0013_rename_state_of_expression_expression_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='grouping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='protocol',
            field=models.ForeignKey(help_text='reference to the protocol used to make the description;            this will define which Traits will be available', on_delete=django.db.models.deletion.PROTECT, related_name='descriptions', to='describe.protocol'),
        ),
    ]
