# Generated by Django 5.1.7 on 2025-03-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0013_protocol_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ('order', 'name')},
        ),
    ]
