# Generated by Django 4.0.4 on 2022-08-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0014_trait_grouping_alter_description_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='related_states',
            field=models.ManyToManyField(to='describe.state'),
        ),
    ]
