# Generated by Django 5.2.1 on 2025-06-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0015_auto_20250624_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.CharField(help_text='The identifier of the description', max_length=200, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.CharField(help_text='A descriptive, unique, and unambiguous name', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='numeric_id',
            field=models.IntegerField(help_text='Numbering code', verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='trait',
            constraint=models.UniqueConstraint(models.F('numeric_id'), models.F('protocol'), name='unique_numeric_id_per_protocol'),
        ),
    ]
