# Generated by Django 5.2 on 2025-07-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0016_alter_description_name_alter_trait_description_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='trait',
            name='unique_numeric_id_per_protocol',
            constraint=models.UniqueConstraint(models.F('numeric_id'), models.F('protocol'), name='unique_numeric_id_per_protocol', violation_error_message='Each protocol must have unique Descriptor IDs. This one is already used.'),
        ),
    ]
