# Generated by Django 5.2 on 2026-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("describe", "0017_alter_trait_unique_numeric_id_per_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="description",
            name="notes",
            field=models.CharField(
                blank=True, default="", help_text="Notes relative to the description", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="description",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
