# Generated by Django 5.2 on 2026-01-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0019_backfill_description_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Notes relative to the description', max_length=500),
        ),
        migrations.AlterField(
            model_name='description',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
