# Generated by Django 6.0.4 on 2026-05-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0020_alter_description_created_at_alter_description_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='describe.stategroup'),
        ),
    ]
