# Generated by Django 6.0.4 on 2026-05-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0022_auto_20260425_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='describe.stategroup'),
        ),
        migrations.AlterField(
            model_name='state',
            name='related_states',
            field=models.ManyToManyField(blank=True, to='describe.state'),
        ),
    ]
