# Generated by Django 6.0.4 on 2026-05-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0025_auto_20260514_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='name',
        ),
        migrations.AlterField(
            model_name='description',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descriptions', to='describe.descriptionlabel'),
        ),
    ]
