# Generated by Django 4.1.2 on 2022-10-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('length', models.FloatField(help_text='The length of the area, in meters.')),
                ('width', models.FloatField(help_text='The width of the area, in meters.')),
                ('order', models.PositiveIntegerField(help_text='The ordering of the area within its location')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.location')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
