# Generated by Django 3.2.12 on 2022-03-03 21:16

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='garden',
        ),
        migrations.AddField(
            model_name='area',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='spaces.location'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Garden',
        ),
    ]
