# Generated by Django 4.2.2 on 2023-07-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
