# Generated by Django 3.2.12 on 2022-03-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_auto_20220303_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
    ]
