# Generated by Django 5.2 on 2025-05-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_location_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cols',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='area',
            name='length',
            field=models.FloatField(help_text='The length of the area, in meters'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='The identificative name of the area', max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The ordering of the area within its location'),
        ),
        migrations.AlterField(
            model_name='area',
            name='width',
            field=models.FloatField(help_text='The width of the area, in meters'),
        ),
    ]
