# Generated by Django 3.2.12 on 2022-04-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_area_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='temp_offset',
        ),
    ]
