# Generated by Django 3.2.12 on 2022-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_auto_20220425_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='length',
            field=models.FloatField(help_text='The length of the area, in meters.'),
        ),
        migrations.AlterField(
            model_name='area',
            name='width',
            field=models.FloatField(help_text='The width of the area, in meters.'),
        ),
    ]
