# Generated by Django 3.2.12 on 2022-04-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_auto_20220426_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='The ordering of the area within its location'),
            preserve_default=False,
        ),
    ]
