# Generated by Django 3.2.12 on 2022-05-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_area_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['order', 'name']},
        ),
    ]
