# Generated by Django 3.2.12 on 2022-05-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_alter_area_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.location'),
        ),
    ]
