# Generated by Django 4.1.2 on 2022-10-29 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cart', help_text='An identificative name for your cart', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoragePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collect.storage')),
            ],
        ),
        migrations.CreateModel(
            name='SeedSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.PositiveIntegerField(help_text='An unique identificative number of the seed sample', unique=True, verbose_name='ID')),
                ('notes', models.CharField(blank=True, default='', help_text='Notes relative to the seed sample', max_length=500, null=True)),
                ('growing_season', models.IntegerField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collect.storageposition')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.plantvariety')),
            ],
            options={
                'ordering': ['-sample_id'],
            },
        ),
        migrations.CreateModel(
            name='SampleWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='sample weight (g)')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('seedsample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.seedsample')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Germinability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germinability', models.IntegerField()),
                ('after_days', models.IntegerField(blank=True, null=True)),
                ('performed_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('seedsample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.seedsample')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='quantity retrieved (g)')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.cart')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.seedsample')),
            ],
            options={
                'ordering': ['sample__position'],
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='unique_user_active'),
        ),
    ]
