# Generated by Django 3.2.12 on 2022-03-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0004_auto_20201226_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(help_text='Notes relative to the seed sample', max_length=500)),
                ('growing_season', models.IntegerField(blank=True)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.plantvariety')),
            ],
        ),
        migrations.CreateModel(
            name='SampleWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('seedsample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.seedsample')),
            ],
        ),
        migrations.CreateModel(
            name='Germinability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('after_days', models.IntegerField()),
                ('performed_at', models.DateTimeField()),
                ('seedsample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.seedsample')),
            ],
        ),
    ]
