# Generated by Django 3.2.12 on 2022-03-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germinability',
            name='after_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='germinability',
            name='performed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
