# Generated by Django 4.2.4 on 2023-12-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collect", "0002_storage_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageposition",
            name="storage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="collect.storage"
            ),
        ),
    ]
