# Generated by Django 5.1.7 on 2025-03-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_alter_storageposition_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-active', 'name')},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('sample__position',)},
        ),
        migrations.AlterModelOptions(
            name='germinability',
            options={'ordering': ('-performed_at',)},
        ),
        migrations.AlterModelOptions(
            name='sampleweight',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='seedsample',
            options={'ordering': ('-sample_id',)},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ('name',), 'verbose_name_plural': 'Storage'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seedsample',
            name='notes',
            field=models.CharField(default='', help_text='Notes relative to the seed sample', max_length=500),
        ),
    ]
