# Generated by Django 3.2.12 on 2022-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20220304_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germinability',
            name='performed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
