# Generated by Django 3.2.12 on 2022-03-09 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_alter_germinability_performed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleweight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleweight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
