# Generated by Django 5.1.7 on 2025-03-25 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_alter_cart_options_alter_cartitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-is_active', 'name')},
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_user_active',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='cart',
            name='default_weight',
            field=models.FloatField(default=10, help_text='Default quantity to retrieve (g)'),
        ),
        migrations.AlterField(
            model_name='seedsample',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Notes relative to the seed sample', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_user_active'),
        ),
    ]
