# Generated by Django 5.2 on 2025-04-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_alter_cart_options_remove_cart_unique_user_active_and_more'),
        ('register', '0013_alter_plantspecies_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeedSample',
            new_name='Sample',
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-sample_id',), 'verbose_name': 'sample'},
        ),
        migrations.RenameField(
            model_name='germinability',
            old_name='seedsample',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='sampleweight',
            old_name='seedsample',
            new_name='sample',
        ),
    ]
