# Generated by Django 3.2.12 on 2022-03-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_auto_20220309_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleweight',
            name='updated_at',
        ),
    ]
