# Generated by Django 3.2.12 on 2022-03-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_remove_sampleweight_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleweight',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
