# Generated by Django 5.2 on 2025-04-26 09:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_rename_seedsample_sample_alter_sample_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='germinability',
            options={'ordering': ('performed_at',)},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-sample_id',)},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collect.sample'),
        ),
        migrations.AlterField(
            model_name='germinability',
            name='performed_at',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='sampleweight',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='sampleweight',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='sample weight (g)'),
        ),
    ]
