# Generated by Django 3.2.12 on 2022-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0007_alter_sampleweight_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='germinability',
            options={'ordering': ['performed_at']},
        ),
        migrations.AlterField(
            model_name='germinability',
            name='value',
            field=models.IntegerField(),
        ),
    ]
