# Generated by Django 5.2 on 2025-12-02 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0007_alter_germinability_options_alter_sample_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ('name',), 'verbose_name_plural': 'storage'},
        ),
        migrations.AlterField(
            model_name='sampleweight',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='recorded at'),
        ),
    ]
