# Generated by Django 5.2 on 2026-02-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_alter_storage_options_alter_sampleweight_created_at'),
        ('register', '0014_alter_entity_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='kind',
            field=models.CharField(choices=[('W', 'Withdrawal'), ('D', 'Discard')], db_index=True, default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='sample',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Discarded')], db_index=True, default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='quantity retrieved (g)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='collect.storageposition'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'sample'), name='uniq_cart_sample'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'A'), ('discarded_at__isnull', True)), models.Q(('status', 'D'), ('discarded_at__isnull', False)), _connector='OR'), name='sample_status_discarded_at_consistent'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'A'), ('position__isnull', False)), models.Q(('status', 'D'), ('position__isnull', True)), _connector='OR'), name='sample_status_position_consistent'),
        ),
    ]
