# Generated by Django 3.2.12 on 2022-03-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_auto_20220309_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleweight',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='seedsample',
            name='notes',
            field=models.CharField(blank=True, help_text='Notes relative to the seed sample', max_length=500, null=True),
        ),
    ]
