# Generated by Django 3.2.12 on 2022-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0009_auto_20220309_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
