# Generated by Django 6.0.4 on 2026-04-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0009_cart_kind_sample_discarded_at_sample_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='default_weight',
            field=models.FloatField(default=10, help_text='Default quantity to withdraw (g)'),
        ),
    ]
