# Generated by Django 3.2.12 on 2022-03-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0010_alter_storage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedsample',
            name='growing_season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
