# Generated by Django 6.0.4 on 2026-05-30 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0010_alter_cart_default_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germinability',
            name='performed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='sampleweight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='recorded at'),
        ),
    ]
