# Generated by Django 3.2.12 on 2022-03-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0011_alter_seedsample_growing_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedsample',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
