# Generated by Django 6.0.4 on 2026-06-26 07:12

from django.db import migrations, models


def validate_numeric_names(apps, schema_editor):
    StoragePosition = apps.get_model("collect", "StoragePosition")

    bad = []
    for pk, name in StoragePosition.objects.values_list("pk", "name").iterator():
        if not str(name).isdigit():
            bad.append((pk, name))

    if bad:
        raise ValueError(
            "StoragePosition.name contains non-numeric values: "
            + ", ".join(f"id={pk!r} name={name!r}" for pk, name in bad[:20])
        )


class Migration(migrations.Migration):
    dependencies = [
        ("collect", "0011_alter_germinability_performed_at_and_more"),
    ]

    operations = [
        migrations.RunPython(validate_numeric_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="storageposition",
            name="name",
            field=models.PositiveIntegerField(),
        ),
    ]
