# Generated by Django 3.2.12 on 2022-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0012_alter_seedsample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedsample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
