# Generated by Django 3.2.12 on 2022-03-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0013_alter_seedsample_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedsample',
            name='sample_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
