# Generated by Django 3.2.12 on 2022-03-29 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0014_seedsample_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedsample',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collect.storageposition'),
        ),
    ]
