# Generated by Django 3.2.12 on 2022-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0015_alter_seedsample_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedsample',
            name='sample_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
