# Generated by Django 3.2.12 on 2022-03-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0016_alter_seedsample_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleweight',
            name='value',
            field=models.FloatField(verbose_name='sample weight (g)'),
        ),
    ]
