# Generated by Django 3.2.12 on 2022-03-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0017_alter_sampleweight_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='germinability',
            old_name='value',
            new_name='germinability',
        ),
        migrations.RenameField(
            model_name='sampleweight',
            old_name='value',
            new_name='weight',
        ),
    ]
