# Generated by Django 3.2.12 on 2022-04-08 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collect', '0018_auto_20220329_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='germinability',
            options={'ordering': ['-performed_at']},
        ),
        migrations.AlterModelOptions(
            name='seedsample',
            options={'ordering': ['-sample_id']},
        ),
        migrations.AlterField(
            model_name='germinability',
            name='performed_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='seedsample',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Notes relative to the seed sample', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='quantity retrieved (g)')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.cart')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.seedsample')),
            ],
        ),
    ]
