# Generated by Django 3.2.12 on 2022-04-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0019_auto_20220408_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['sample__position']},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.FloatField(default=0, verbose_name='quantity retrieved (g)'),
        ),
    ]
