# Generated by Django 3.2.12 on 2022-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0020_auto_20220423_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='Cart', help_text='An identificative name for your cart', max_length=100),
        ),
    ]
