# Generated by Django 3.2.12 on 2022-04-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0021_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='unique_active'),
        ),
    ]
