# Generated by Django 3.2.12 on 2022-04-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0022_auto_20220426_1027'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_active',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='unique_user_active'),
        ),
    ]
