# Generated by Django 3.2.12 on 2022-05-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0024_auto_20220430_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedsample',
            name='sample_id',
            field=models.PositiveIntegerField(help_text='An unique identificative number of the seed sample', unique=True, verbose_name='ID'),
        ),
    ]
