# Generated by Django 3.2.12 on 2022-02-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('temp_offset', models.IntegerField()),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.garden')),
            ],
        ),
    ]
