from django.urls import path

from .views.autocomplete import CropLayoutAutocompleteView
from .views.crop import CropDeleteView, CropSort, crop_detail, crop_update
from .views.fieldbook import (
    ParameterTargetCreate,
    ParameterTargetDelete,
    TraitTargetCreate,
    TraitTargetDelete,
    fieldbook_create,
    fieldbook_delete,
    fieldbook_detail,
    fieldbook_list,
    fieldbook_targets_delete,
    fieldbook_update,
    fieldbook_update_display_config,
    fieldbook_update_step_order,
    layout_fieldbook_create,
    parameter_observation_in_step_create,
    parameter_target_observation_create,
    step_detail,
    step_parameter_observations,
    step_parameter_targets,
    step_trait_observations,
    step_trait_targets,
    trait_observation_in_step_create,
    trait_target_observation_create,
)
from .views.layout import (
    layout_archive,
    layout_create,
    layout_crop_create,
    layout_delete,
    layout_detail,
    layout_list,
    layout_management_create,
    layout_restore,
    layout_update,
    location_layout_create,
)
from .views.observation import (
    parameter_observation_create,
    parameter_observation_delete,
    parameter_observation_list,
    parameter_observation_update,
    trait_observation_create,
    trait_observation_delete,
    trait_observation_list,
    trait_observation_update,
)

app_name = "calculator"

urlpatterns = [
    path("observations/traits", trait_observation_list, name="trait_observation_list"),
    path("observations/parameters", parameter_observation_list, name="parameter_observation_list"),
    path("locations/<int:location_id>/layouts/create", location_layout_create, name="location_layout_create"),
    path("layouts/create", layout_create, name="layout_create"),
    path("layouts", layout_list, name="croplayout_list"),
    path("layouts/autocomplete", CropLayoutAutocompleteView.as_view(), name="croplayout_autocomplete"),
    path("layouts/<int:pk>", layout_detail, name="layout_detail"),
    path("layouts/<int:pk>/update", layout_update, name="layout_update"),
    path("layouts/<int:pk>/archive", layout_archive, name="layout_archive"),
    path("layouts/<int:pk>/restore", layout_restore, name="layout_restore"),
    path("layouts/<int:pk>/delete", layout_delete, name="layout_delete"),
    path("layouts/<int:layout_id>/crops/create", layout_crop_create, name="layout_crop_create"),
    path("layouts/<int:layout_id>/management/create", layout_management_create, name="layout_management_create"),
    path("layouts/<int:layout_id>/fieldbooks/create", layout_fieldbook_create, name="layout_fieldbook_create"),
    path("crop/<int:pk>", crop_detail, name="crop_detail"),
    path(
        "crop/<int:crop_id>/observations/expression/create",
        trait_observation_create,
        name="observation_expression_create",
    ),
    path("observations/trait/<int:pk>/update", trait_observation_update, name="trait_observation_update"),
    path("observations/trait/<int:pk>/delete", trait_observation_delete, name="trait_observation_delete"),
    path(
        "crops/<int:crop_id>/observations/parameter/create",
        parameter_observation_create,
        name="observation_parameter_create",
    ),
    path(
        "observations/parameter/<int:pk>/update",
        parameter_observation_update,
        name="parameter_observation_update",
    ),
    path(
        "observations/parameter/<int:pk>/delete",
        parameter_observation_delete,
        name="parameter_observation_delete",
    ),
    path("crops/sort", CropSort.as_view(), name="crop_sort"),
    path("crops/<int:pk>/update", crop_update, name="crop_update"),
    path("crops/<int:pk>/delete", CropDeleteView.as_view(), name="crop_delete"),
    path("fieldbooks", fieldbook_list, name="fieldbook_list"),
    path("fieldbooks/create", fieldbook_create, name="fieldbook_create"),
    path("fieldbooks/<int:pk>", fieldbook_detail, name="fieldbook_detail"),
    path("fieldbooks/<int:pk>/update", fieldbook_update, name="fieldbook_update"),
    path("fieldbooks/<int:pk>/delete", fieldbook_delete, name="fieldbook_delete"),
    path("fieldbooks/<int:pk>/display", fieldbook_update_display_config, name="fieldbook_detail_display"),
    path("fieldbooks/<int:pk>/update/order", fieldbook_update_step_order, name="fieldbook_update_step_order"),
    path(
        "fieldbooks/<int:fieldbook_id>/targets/delete",
        fieldbook_targets_delete,
        name="fieldbook_targets_delete",
    ),
    path("steps/<int:pk>", step_detail, name="step_detail"),
    path("steps/<int:pk>/targets/traits", step_trait_targets, name="step_trait_targets"),
    path("steps/<int:pk>/targets/parameters", step_parameter_targets, name="step_parameter_targets"),
    path("steps/<int:pk>/observations/traits", step_trait_observations, name="step_trait_observations"),
    path(
        "steps/<int:pk>/observations/parameters",
        step_parameter_observations,
        name="step_parameter_observations",
    ),
    path("target/trait/<int:fieldbook_id>", TraitTargetCreate.as_view(), name="trait_target_create"),
    path("target/trait/<int:pk>/delete", TraitTargetDelete.as_view(), name="trait_target_delete"),
    path(
        "target/trait/<int:pk>/observation/create",
        trait_target_observation_create,
        name="trait_target_observation_create",
    ),
    path("target/parameter/<int:pk>/delete", ParameterTargetDelete.as_view(), name="parameter_target_delete"),
    path(
        "target/parameter/<int:pk>/observation/create",
        parameter_target_observation_create,
        name="parameter_target_observation_create",
    ),
    path("target/parameter/<int:fieldbook_id>", ParameterTargetCreate.as_view(), name="parameter_target_create"),
    path(
        "steps/<int:step_id>/traitobservation/create",
        trait_observation_in_step_create,
        name="trait_observation_in_step_create",
    ),
    path(
        "steps/<int:step_id>/parameterobservation/create",
        parameter_observation_in_step_create,
        name="parameter_observation_in_step_create",
    ),
]
