# Generated by Django 4.1.2 on 2022-10-29 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('IN', 'Individual'), ('PA', 'Parnership'), ('CO', 'Company'), ('CP', 'Cooperative')], max_length=2, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('contact', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100, unique=True)),
                ('latin_name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(choices=[('tree', 'Tree'), ('shrub', 'Shrub'), ('vegetable', 'Vegetable'), ('herbaceous', 'Herbaceous')], max_length=100)),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='PlantVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the variety', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.entity')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variety', to='register.plantspecies')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PBR', "Plant Breeders' Right"), ('NLI', 'National Listing'), ('CAT', 'Common Catalogue')], max_length=3)),
                ('status', models.CharField(blank=True, choices=[('G', 'Granted'), ('T', 'Terminated'), ('A', 'Active Application'), ('W', 'Withdrawn'), ('R', 'Refused')], max_length=1, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='register.entity')),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintainers', to='register.entity')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.plantvariety')),
            ],
            options={
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='PlantVarietyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('change_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='register.plantvariety')),
            ],
            options={
                'ordering': ['-change_date'],
            },
        ),
    ]
