# Generated by Django 3.1.4 on 2020-12-06 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantSpecies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("common_name", models.CharField(max_length=100)),
                ("latin_name", models.CharField(max_length=100)),
                (
                    "plant_type",
                    models.CharField(
                        choices=[
                            ("tree", "Tree"),
                            ("shrub", "Shrub"),
                            ("vegetable", "Vegetable"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantVariety",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variety",
                        to="register.plantspecies",
                    ),
                ),
            ],
        ),
    ]
