# Generated by Django 4.2.4 on 2023-08-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protection",
            name="applicants",
            field=models.ManyToManyField(
                blank=True, related_name="applicants", to="register.entity"
            ),
        ),
        migrations.AlterField(
            model_name="protection",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="register.entity",
            ),
        ),
    ]
