# Generated by Django 3.1.4 on 2020-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantspecies',
            options={'ordering': ['common_name']},
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='plant_type',
            field=models.CharField(choices=[('tree', 'Tree'), ('shrub', 'Shrub'), ('vegetable', 'Vegetable'), ('herbaceous', 'Herbaceous')], max_length=100),
        ),
    ]
