# Generated by Django 3.1.4 on 2020-12-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201207_2033'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plantvariety',
            constraint=models.UniqueConstraint(fields=('species', 'name'), name='unique name'),
        ),
    ]
