# Generated by Django 4.2.4 on 2023-08-21 08:51

from django.db import migrations


def copy_applicant_data(apps, schema_editor):
    Protection = apps.get_model("register", "Protection")
    for protection in Protection.objects.all():
        if protection.applicant:
            protection.applicants.add(protection.applicant)
            protection.save()


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0002_protection_applicants_alter_protection_applicant"),
    ]

    operations = [
        migrations.RunPython(copy_applicant_data),
    ]
