# Generated by Django 3.1.4 on 2020-12-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201220_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantspecies',
            name='common_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
