# Generated by Django 4.2.4 on 2023-08-21 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0003_auto_20230821_0851"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protection",
            name="applicant",
        ),
    ]
