# Generated by Django 3.2.12 on 2022-03-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20201226_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantvariety',
            options={'ordering': ['name']},
        ),
    ]
