# Generated by Django 4.2.4 on 2023-08-21 13:59

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0004_remove_protection_applicant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entity",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IN", "Individual"),
                    ("PA", "Partnership"),
                    ("CO", "Company"),
                    ("CP", "Cooperative"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="protection",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
