# Generated by Django 4.2.4 on 2023-09-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0005_alter_entity_options_alter_entity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protection",
            name="maintainers",
            field=models.ManyToManyField(blank=True, to="register.entity"),
        ),
        migrations.AlterField(
            model_name="protection",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("G", "Granted"),
                    ("T", "Terminated"),
                    ("A", "Active Application"),
                    ("W", "Withdrawn"),
                    ("R", "Refused"),
                    ("S", "Surrendered"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
