# Generated by Django 3.2.12 on 2022-03-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_plantvariety_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantVarietyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='plantvariety',
            options={'ordering': ['names__name']},
        ),
        migrations.RemoveConstraint(
            model_name='plantvariety',
            name='unique name',
        ),
        migrations.RemoveField(
            model_name='plantvariety',
            name='name',
        ),
        migrations.AddField(
            model_name='plantvarietyname',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='register.plantvariety'),
        ),
    ]
