# Generated by Django 3.2.12 on 2022-03-23 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20220323_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantvariety',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantvariety',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plantvarietyname',
            name='change_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
