# Generated by Django 4.2.4 on 2023-09-16 15:20

from django.db import migrations

def copy_maintainer_data(apps, schema_editor):
    Protection = apps.get_model("register", "Protection")
    for protection in Protection.objects.all():
        if protection.maintainer:
            protection.maintainers.add(protection.maintainer)
            protection.save()

class Migration(migrations.Migration):
    dependencies = [
        ("register", "0006_protection_maintainers_alter_protection_status"),
    ]

    operations = [
        migrations.RunPython(copy_maintainer_data),
    ]
