# Generated by Django 4.2.4 on 2023-09-16 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0007_auto_20230916_1520"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protection",
            name="maintainer",
        ),
    ]
