# Generated by Django 3.2.12 on 2022-03-24 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20220323_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantvarietyname',
            name='change_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
