# Generated by Django 3.2.12 on 2022-04-23 10:24

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    # Get the newest associated PlantVarietyName instance to set the new property 'name'
    # We get the model from the versioned app registry; if we directly import
    # it, it'll be the wrong version
    PlantVariety = apps.get_model("register", "PlantVariety")
    db_alias = schema_editor.connection.alias
    for var in PlantVariety.objects.using(db_alias).all():
        var.name = var.names.first().name
        var.save()

def reverse_func(apps, schema_editor):
    # We don't need to do anything here, as the field will be deleted by
    # reversing this migration
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_plantvarietyname_change_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantvarietyname',
            options={'ordering': ['-change_date']},
        ),
        migrations.AddField(
            model_name='plantvariety',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
