# Generated by Django 4.2.4 on 2023-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0008_remove_protection_maintainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="protection",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Add any additional information here.",
                max_length=512,
            ),
        ),
    ]
