# Generated by Django 4.2 on 2024-02-26 09:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_protection_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('name',), 'verbose_name': 'entity', 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='plantspecies',
            options={'ordering': ['common_name'], 'verbose_name': 'plant', 'verbose_name_plural': 'plants'},
        ),
        migrations.AlterModelOptions(
            name='plantvariety',
            options={'ordering': ['name'], 'verbose_name': 'variety', 'verbose_name_plural': 'varieties'},
        ),
        migrations.AlterModelOptions(
            name='plantvarietyname',
            options={'ordering': ['-change_date'], 'verbose_name': 'denomination', 'verbose_name_plural': 'denominations'},
        ),
        migrations.AlterField(
            model_name='entity',
            name='contact',
            field=models.CharField(blank=True, help_text='Contact details of the entity, such as phone number or address.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country where the entity is based or operates.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, help_text="Email address of the entity. E.g., 'john.doe@example.com'.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(help_text="Name of the entity. E.g., 'John Doe', 'Doe & Partners', etc.", max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(blank=True, choices=[('IN', 'Individual'), ('PA', 'Partnership'), ('CO', 'Company'), ('CP', 'Cooperative')], help_text='Type of the entity. Choose from the available options.', max_length=2, null=True),
        ),
    ]
