# Generated by Django 4.2 on 2024-04-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_entity_options_alter_plantspecies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protection',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
