# Generated by Django 3.2.12 on 2022-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_plantvariety_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantvariety',
            name='name',
            field=models.CharField(help_text='The name of the variety', max_length=100),
        ),
    ]
