# Generated by Django 3.2.12 on 2022-05-12 19:31

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_plantvariety_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('IN', 'Individual'), ('PA', 'Parnership'), ('CO', 'Company'), ('CP', 'Cooperative')], max_length=2)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('contact', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PBR', "Plant Breeders' Right"), ('NLI', 'National Listing'), ('CAT', 'Common Catalogue')], max_length=3)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('reference', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='register.entity')),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintainers', to='register.entity')),
            ],
        ),
        migrations.AddField(
            model_name='plantvariety',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='register.entity'),
        ),
    ]
