# Generated by Django 5.1.3 on 2024-11-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0011_alter_protection_date_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantspecies",
            options={
                "ordering": ["common_name"],
                "verbose_name": "plant species",
                "verbose_name_plural": "plant species",
            },
        ),
    ]
