# Generated by Django 5.1.6 on 2025-03-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0012_alter_plantspecies_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantspecies",
            options={
                "ordering": ("common_name",),
                "verbose_name": "plant species",
                "verbose_name_plural": "plant species",
            },
        ),
        migrations.AlterModelOptions(
            name="plantvariety",
            options={
                "ordering": ("name",),
                "verbose_name": "variety",
                "verbose_name_plural": "varieties",
            },
        ),
        migrations.AlterModelOptions(
            name="plantvarietyname",
            options={
                "ordering": ("-change_date",),
                "verbose_name": "denomination",
                "verbose_name_plural": "denominations",
            },
        ),
        migrations.AlterModelOptions(
            name="protection",
            options={"ordering": ("-date_start",)},
        ),
        migrations.AlterField(
            model_name="entity",
            name="contact",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Contact details of the entity, such as phone number or address.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="email",
            field=models.EmailField(
                default="",
                help_text="Email address of the entity. E.g., 'john.doe@example.com'.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IN", "Individual"),
                    ("PA", "Partnership"),
                    ("CO", "Company"),
                    ("CP", "Cooperative"),
                ],
                default="",
                help_text="Type of the entity. Choose from the available options.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="plantvariety",
            name="breeder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="register.entity",
            ),
        ),
        migrations.AlterField(
            model_name="protection",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="protection",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("G", "Granted"),
                    ("T", "Terminated"),
                    ("A", "Active Application"),
                    ("W", "Withdrawn"),
                    ("R", "Refused"),
                    ("S", "Surrendered"),
                ],
                default="",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="protection",
            name="type",
            field=models.CharField(
                choices=[
                    ("PBR", "Plant Breeders' Rights"),
                    ("NLI", "National Listing"),
                    ("CAT", "Common Catalogue"),
                ],
                max_length=3,
            ),
        ),
    ]
