# Generated by Django 3.2.12 on 2022-05-13 12:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20220512_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='protection',
            name='variety',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.plantvariety'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(blank=True, choices=[('IN', 'Individual'), ('PA', 'Parnership'), ('CO', 'Company'), ('CP', 'Cooperative')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='protection',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
