# Generated by Django 5.2 on 2025-12-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_alter_plantspecies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="Email address of the entity. E.g., 'john.doe@example.com'.", max_length=254),
        ),
    ]
