# Generated by Django 3.2.12 on 2022-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20220513_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protection',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
