# Generated by Django 3.2.12 on 2022-05-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_protection_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protection',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='register.entity'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintainers', to='register.entity'),
        ),
    ]
