# Generated by Django 3.2.12 on 2022-05-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20220519_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantvariety',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.entity'),
        ),
    ]
