# Generated by Django 3.2.12 on 2022-05-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_alter_plantvariety_breeder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protection',
            options={'ordering': ['-date_start']},
        ),
        migrations.AlterField(
            model_name='plantvariety',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.entity'),
        ),
        migrations.AlterField(
            model_name='plantvariety',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variety', to='register.plantspecies'),
        ),
    ]
