# Generated by Django 6.0.4 on 2026-05-29 20:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_rename_protection_type_and_alter_protection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protections', to='register.protectiontype'),
        ),
        migrations.AlterField(
            model_name='protectiontype',
            name='code',
            field=models.CharField(help_text='An identificative three-letter code of the protection type', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}\\Z', 'It must be a three-letter code.')]),
        ),
        migrations.AlterField(
            model_name='protectiontype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='protectiontype',
            name='name',
            field=models.CharField(help_text='An identificative name of the protection type', max_length=100),
        ),
    ]
