# Generated by Django 4.0.4 on 2022-06-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20220520_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='protection',
            name='status',
            field=models.CharField(blank=True, choices=[('G', 'Granted'), ('T', 'Terminated'), ('A', 'Active Application'), ('W', 'Withdrawn'), ('R', 'Refused')], max_length=1, null=True),
        ),
    ]
