# Generated by Django 6.0.4 on 2026-09-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_protection_type_alter_protectiontype_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantspecies',
            old_name='latin_name',
            new_name='botanical_name',
        ),
        migrations.RemoveField(
            model_name='plantspecies',
            name='plant_type',
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
