# Generated by Django 4.1.2 on 2022-10-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('parameters', '0001_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, help_text='Notes relative to the Crop', max_length=500, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.area')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.plantspecies')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.plantvariety')),
            ],
            options={
                'ordering': ['species', 'variety'],
            },
        ),
        migrations.CreateModel(
            name='ManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.crop')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.managementtype')),
            ],
        ),
        migrations.CreateModel(
            name='CropParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('url_ref', models.URLField(blank=True, help_text='a url reference for the source of the parameter', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='calculator.crop')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parameters.parameter')),
            ],
            options={
                'ordering': ['parameter__code'],
            },
        ),
    ]
