# Generated by Django 5.0.7 on 2024-08-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropparameter',
            name='note',
            field=models.CharField(blank=True, help_text='Add any additional information here.', max_length=512),
        ),
    ]
