# Generated by Django 3.2.12 on 2022-03-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0009_rename_cropparameter_speciesparameter'),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('url_ref', models.URLField(help_text='a url reference for the source of the parameter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.crop')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parameters.parameter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
