# Generated by Django 3.2.12 on 2022-03-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_cropparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='notes',
            field=models.CharField(blank=True, help_text='Notes relative to the Crop', max_length=500, null=True),
        ),
    ]
