# Generated by Django 3.2.12 on 2022-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_crop_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropparameter',
            name='url_ref',
            field=models.URLField(blank=True, help_text='a url reference for the source of the parameter', null=True),
        ),
    ]
