# Generated by Django 3.2.12 on 2022-03-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_area_options'),
        ('calculator', '0004_alter_cropparameter_url_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.area')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.managementtype')),
            ],
        ),
    ]
