# Generated by Django 3.2.12 on 2022-03-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_management_managementtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='area',
        ),
        migrations.AddField(
            model_name='management',
            name='crop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calculator.crop'),
            preserve_default=False,
        ),
    ]
