# Generated by Django 3.2.12 on 2022-03-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20220324_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managementtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
