# Generated by Django 3.2.12 on 2022-04-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20220328_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropparameter',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='calculator.crop'),
        ),
    ]
