# Generated by Django 6.0.4 on 2026-09-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_parameterobservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementtype',
            options={'ordering': ('name', 'pk'), 'verbose_name_plural': 'management operations'},
        ),
    ]
