# Generated by Django 3.2.12 on 2022-04-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_remove_area_temp_offset'),
        ('calculator', '0008_alter_cropparameter_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.area'),
        ),
    ]
