# Generated by Django 6.0.4 on 2026-09-13 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_alter_managementtype_options'),
        ('describe', '0026_remove_description_name_alter_description_label'),
        ('parameters', '0009_alter_varietalparameter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametertarget',
            name='required_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)], verbose_name='Repetitions'),
        ),
        migrations.AlterField(
            model_name='traittarget',
            name='required_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)], verbose_name='Repetitions'),
        ),
        migrations.AddConstraint(
            model_name='parametertarget',
            constraint=models.CheckConstraint(condition=models.Q(('required_count__gte', 1)), name='parameter_target_required_count_min_1'),
        ),
        migrations.AddConstraint(
            model_name='traittarget',
            constraint=models.CheckConstraint(condition=models.Q(('required_count__gte', 1)), name='trait_target_required_count_min_1'),
        ),
    ]
