# Generated by Django 3.2.12 on 2022-05-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_alter_crop_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['content_type', 'object_id']},
        ),
    ]
