# Generated by Django 3.2.12 on 2022-05-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_plantvariety_name'),
        ('calculator', '0010_alter_crop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.plantspecies'),
        ),
        migrations.AddField(
            model_name='crop',
            name='variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.plantvariety'),
        ),
    ]
