# Generated by Django 3.2.12 on 2022-05-08 09:05

from django.db import migrations

def migrate_species_or_variety(apps, schema_editor):
    Crop = apps.get_model('calculator', 'Crop')
    PlantSpecies = apps.get_model('register', 'PlantSpecies')
    PlantVariety = apps.get_model('register', 'PlantVariety')
    for crop in Crop.objects.all():
        if crop.content_type.model == 'plantvariety':
            variety = PlantVariety.objects.get(pk=crop.object_id)
            crop.variety = variety
            crop.species = variety.species
            crop.save()
        elif crop.content_type.model == 'plantspecies':
            crop.species = PlantSpecies.objects.get(pk=crop.object_id)
            crop.save()
        else:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_auto_20220508_0905'),
        ('register', '0011_alter_plantvariety_name'),
    ]

    operations = [
        migrations.RunPython(migrate_species_or_variety),
    ]
