# Generated by Django 3.2.12 on 2022-05-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_auto_20220508_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['species', 'variety']},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='object_id',
        ),
    ]
