# Generated by Django 3.2.12 on 2022-05-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0012_auto_20220423_1024'),
        ('calculator', '0013_auto_20220508_1232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cropparameter',
            unique_together={('parameter', 'crop')},
        ),
    ]
