# Generated by Django 4.0.4 on 2022-06-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_protection_status'),
        ('calculator', '0014_alter_cropparameter_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropparameter',
            options={'ordering': ['parameter__code']},
        ),
        migrations.AlterUniqueTogether(
            name='cropparameter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.plantspecies'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.plantvariety'),
        ),
    ]
