# Generated by Django 4.1.2 on 2022-10-29 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('describe', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='A code to identify the parameter.', max_length=50, unique=True)),
                ('name', models.CharField(help_text='The name of the parameter.', max_length=200)),
                ('description', models.CharField(help_text='The description of the parameter.', max_length=200)),
                ('measure_unit', models.CharField(help_text='The unit of measurement.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VarietalParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('url_ref', models.URLField(blank=True, help_text='a url reference for the source of the parameter', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parameters.parameter')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parameters', to='register.plantvariety')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciesParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('url_ref', models.URLField(blank=True, help_text='a url reference for the source of the parameter', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parameters.parameter')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parameters', to='register.plantspecies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('georeference_lat', models.FloatField()),
                ('georeference_lon', models.FloatField()),
                ('measure_unit', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='describe.trait')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='register.plantvariety')),
            ],
        ),
    ]
