# Generated by Django 3.1.4 on 2020-12-13 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("describe", "0008_auto_20201213_2007"),
        ("register", "0002_auto_20201207_2033"),
    ]

    operations = [
        migrations.CreateModel(
            name="VarietalParameter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="register.plantvariety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("georeference_lat", models.FloatField()),
                ("georeference_lon", models.FloatField()),
                ("measure_unit", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="describe.trait"
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="register.plantvariety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropParameter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="the name of the parameter", max_length=200
                    ),
                ),
                ("measure_unit", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                (
                    "url_ref",
                    models.URLField(
                        help_text="a url reference for the source of the parameter"
                    ),
                ),
                (
                    "specie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="register.plantspecies",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
