# Generated by Django 4.0.4 on 2023-02-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
