# Generated by Django 3.1.4 on 2020-12-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropparameter',
            name='url_ref',
        ),
        migrations.RemoveField(
            model_name='cropparameter',
            name='value',
        ),
        migrations.AddField(
            model_name='varietalparameter',
            name='measure_unit',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='varietalparameter',
            name='name',
            field=models.CharField(default=None, help_text='the name of the parameter', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VarietalParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('url_ref', models.URLField(help_text='a url reference for the source of the parameter')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parameters.varietalparameter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CropParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('url_ref', models.URLField(help_text='a url reference for the source of the parameter')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parameters.cropparameter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
