# Generated by Django 4.0.4 on 2023-03-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0001_initial'),
        ('register', '0001_initial'),
        ('parameters', '0002_delete_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('georeference_lat', models.FloatField()),
                ('georeference_lon', models.FloatField()),
                ('measure_unit', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='describe.trait')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='register.plantvariety')),
            ],
        ),
    ]
