# Generated by Django 3.2.18 on 2023-04-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_measure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
