# Generated by Django 3.1.4 on 2020-12-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_auto_20201214_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropparameter',
            name='code',
            field=models.CharField(default=None, help_text='codename of the parameter', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='varietalparameter',
            name='code',
            field=models.CharField(default=None, help_text='codename of the parameter', max_length=50),
            preserve_default=False,
        ),
    ]
