# Generated by Django 4.2.4 on 2023-09-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parameters", "0004_delete_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciesparameter",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Add any additional information here.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="varietalparameter",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Add any additional information here.",
                max_length=512,
            ),
        ),
    ]
