# Generated by Django 5.1.7 on 2025-03-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_speciesparameter_note_varietalparameter_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesparameter',
            name='url_ref',
            field=models.URLField(blank=True, default='', help_text='a url reference for the source of the parameter'),
        ),
        migrations.AlterField(
            model_name='varietalparameter',
            name='url_ref',
            field=models.URLField(blank=True, default='', help_text='a url reference for the source of the parameter'),
        ),
    ]
