# Generated by Django 3.1.4 on 2020-12-14 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201207_2033'),
        ('parameters', '0005_auto_20201214_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='codename of the parameter', max_length=50)),
                ('name', models.CharField(help_text='the name of the parameter', max_length=200)),
                ('description', models.CharField(help_text='long description of the parameter', max_length=200)),
                ('measure_unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='varietalparametervalue',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='cropparameter',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cropparameter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cropparameter',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='cropparameter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='varietalparameter',
            name='code',
        ),
        migrations.RemoveField(
            model_name='varietalparameter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='varietalparameter',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='varietalparameter',
            name='name',
        ),
        migrations.AddField(
            model_name='cropparameter',
            name='url_ref',
            field=models.URLField(default=None, help_text='a url reference for the source of the parameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropparameter',
            name='value',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='varietalparameter',
            name='url_ref',
            field=models.URLField(default=None, help_text='a url reference for the source of the parameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='varietalparameter',
            name='value',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cropparameter',
            name='specie',
        ),
        migrations.AddField(
            model_name='cropparameter',
            name='specie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='register.plantspecies'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='varietalparameter',
            name='variety',
        ),
        migrations.AddField(
            model_name='varietalparameter',
            name='variety',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='register.plantvariety'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CropParameterValue',
        ),
        migrations.DeleteModel(
            name='VarietalParameterValue',
        ),
        migrations.AddField(
            model_name='cropparameter',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='parameters.parameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='varietalparameter',
            name='parameter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='parameters.parameter'),
            preserve_default=False,
        ),
    ]
