# Generated by Django 5.2.1 on 2025-06-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0006_alter_speciesparameter_url_ref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesparameter',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='varietalparameter',
            options={'ordering': ['updated_at']},
        ),
    ]
