# Generated by Django 3.2.12 on 2022-03-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20201226_1323'),
        ('parameters', '0008_auto_20210106_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CropParameter',
            new_name='SpeciesParameter',
        ),
    ]
