# Generated by Django 6.0.4 on 2026-08-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0008_remove_speciesparameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varietalparameter',
            options={'ordering': ['created_at'], 'verbose_name': 'value', 'verbose_name_plural': 'values'},
        ),
    ]
