# Generated by Django 3.2.12 on 2022-03-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0009_rename_cropparameter_speciesparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='code',
            field=models.CharField(help_text='A code to identify the parameter.', max_length=50, unique=True),
        ),
    ]
