# Generated by Django 3.2.12 on 2022-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0010_alter_parameter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesparameter',
            name='url_ref',
            field=models.URLField(blank=True, help_text='a url reference for the source of the parameter', null=True),
        ),
        migrations.AlterField(
            model_name='varietalparameter',
            name='url_ref',
            field=models.URLField(blank=True, help_text='a url reference for the source of the parameter', null=True),
        ),
    ]
