# Generated by Django 3.2.12 on 2022-04-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20220423_1024'),
        ('parameters', '0011_auto_20220320_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesparameter',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parameters', to='register.plantspecies'),
        ),
        migrations.AlterField(
            model_name='varietalparameter',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parameters', to='register.plantvariety'),
        ),
    ]
